### ISSUE TITLE
Can't launch

### ISSUE THREAD

**Issue by cryptolok** [cappsule/cappsule-doc#2]
After installation, I tried to launch `virt exec bash`, but I got:

> Client error: cannot connect to cappsule server.

So I tried to launch the server with `consoleserver`, but:

> `Connection  refused
> 
> handle_notif_msg: read (-1): Bad file descriptor`

Do you have any suggestions?

**Comment by cappsule** [comment]
As mentioned in the [FAQ](https://cappsule.github.io/faq/#error-messages), `daemon` must be launched in order to use `virt`:

```
/usr/local/cappsule/usr/bin/daemon
```

To disable the gui and enable debug:

```
/usr/local/cappsule/usr/bin/daemon --debug --no-gui
```

**Comment by cryptolok** [comment]
I won't open an issue without reading and understanding the documentation.
Starting the daemon with exit status 0 has no effect at all, but I can't see anything wrong with its system calls.
When trying to add `-d` option:

> finit_module: Exec format error

**Comment by cappsule** [comment]
I think that the your kernel version differs from the kernel modules version. Are there any related error messages in `/var/log/kern.log`?

**Comment by cryptolok** [comment]
One thing:

> cappsule_guest: disagrees about version of symbol module_layout

**Comment by cappsule** [comment]
Indeed, you have to build the kernel modules against you running kernel (the different steps are detailed in the [documentation](https://github.com/cappsule/cappsule-doc/blob/master/development.rst)).

**Comment by cryptolok** [comment]
Building modules has itself some issues, but it's off topic for now.
The kernel error message has gone, without any effect however.
When trying to run `daemon -d`

> finit_module: File exists

**Comment by cappsule** [comment]
One of the kernel modules is still loaded. Try `rmmod cappsule_guest cappsule` or `rmmod cappsule cappsule_guest` to remove it.

I you have the possibility to join our [IRC channel](https://cappsule.github.io/contact/#irc), it might be easier to solve these problems :-) By the way, could you open an issue on the [hypervisor repository](https://github.com/cappsule/cappsule-hypervisor) concerning the build issues?

Thanks

**Comment by cryptolok** [comment]
> rmmod cappsule_guest

solves the problem :)
However, I was unable to run it on a VM, actually the import failed, so i converted it to qcow2 and ran on KVM, then I reconverted it back to vmdk and ran on VirtualBox, but it's unable to detect my VMX support for some reason...
Thus, we can consider this issue closed and I will continue to compiling it by moving to hypervisor's repository, as you adviced.
I appreciate your help.
